sonar.projectKey=Notes-App
sonar.projectName=Abu's Notes App
sonar.projectVersion=1.0

sonar.sources=backend,frontend/src
sonar.tests=backend/test

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/public/**
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

sonar.javascript.environments=nodejs,browser
sonar.sourceEncoding=UTF-8